### ISSUE TITLE
[UNIFIED] bitwarden/self-host:2023.9.3-beta High CPU usage

### ISSUE THREAD

**Issue by hardwareadictos** [bitwarden/self-host#164]
Just updated my APP container to 2023.9.3-beta and Bitwarden now is sitting on +- 50% of VM CPU Usage:

![image](https://github.com/bitwarden/self-host/assets/20403906/d7f4ade6-a48b-42af-9ed3-39432eede06f)

As the base image is a very lightweigh Debian, i cannot check processes. Can someone help me with this?

On my test container all seems fine, only 5 users which are using the service as before. My docker-compose file:

```
version: "3.8"

services:
  bitwarden:
    container_name: Bitwarden-PRO
    depends_on:
      - db
    env_file:
      - ./env/bw-settings.env
    image: bitwarden/self-host:2023.9.3-beta
    restart: unless-stopped
    ports:
      - "8085:8080"
    volumes:
      - ./bitwarden:/etc/bitwarden

  db:
    container_name: BitwardenDB-PRO
    env_file:
      - ./env/db-settings.env
    image: mariadb:10
    restart: always
    volumes:
      - ./db:/var/lib/mysql
```

Thanks in advance.

Edit 1: Is even getting worse:

![image](https://github.com/bitwarden/self-host/assets/20403906/b0eed60f-9155-4bbb-bbcd-39d6cb872133)
