### ISSUE TITLE
unable to install - mariadb/postgresql db doesn't change anything

### ISSUE THREAD

**Issue by lukaszzyla** [bitwarden/self-host#200]
INFO exited: admin (terminated by SIGABRT (core dumped); not expected)
Clicking CREATE ACCOUNT on startup page doesn't do anything.

It doesnt matter if I choose to install mariadb or postgres.
my portainer compose and stack.env below:
```
---
version: "3.8"

services:
  bitwarden:
    depends_on:
      - db
    env_file:
      - stack.env
    image: ${REGISTRY:-bitwarden}/self-host:${TAG:-latest}
    restart: always
    ports:
      - "7080:8080"
      - "7443:8443"
    volumes:
      - bitwarden:/etc/bitwarden
      - logs:/var/log/bitwarden



  # PostgreSQL Example
  db:
    environment:
      POSTGRES_USER: "bitwarden"
      POSTGRES_PASSWORD: "super_strong_password"
      POSTGRES_DB: "bitwarden_vault"
    image: postgres:14
    restart: always
    volumes:
      - data:/var/lib/postgresql/data

  # MS SQL Server Example
  # Docs: https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment
  # db:
  #   environment:
  #     MSSQL_SA_PASSWORD: "super_strong_password"
  #     ACCEPT_EULA: Y
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   restart: always
  #   volumes:
  #     - data:/var/opt/mssql

volumes:
  bitwarden:
  logs:
  data:
  
networks:
  default:
    external: true
    name: chw
```

my stack.env added as environment variables in portainer:

```
BW_DOMAIN=sub.domain.com (using outside real fqdn)
BW_DB_PROVIDER=postgresql
BW_DB_SERVER=db
BW_DB_DATABASE=bitwarden_vault
BW_DB_USERNAME=bitwarden
BW_DB_PASSWORD=mysuperstrongpass
BW_INSTALLATION_ID=my id got from bitwarden website
BW_INSTALLATION_KEY=my key got from bitwarden website
COMPOSE_PROJECT_NAME=bitwarden
REGISTRY=bitwarden
TAG=dev
```
