### ISSUE TITLE
feature request: health and readiness endpoints

### ISSUE THREAD

**Issue by georglauterbach** [bitwarden/self-host#218]
I am deploying `docker.io/bitwarden/self-host:2024.1.2-beta` in a Kubernetes cluster with great success. It works flawlessly, and I am genuinely grateful for that. As an improvement to the already existing deployment, I want to propose an internal (listening on `127.0.0.1`) API endpoint that one can query. Authelia, for example, can be checked on `/api/health`. This can then easily be used to write a `startupProbe` or a `readinessProbe`:

```yaml
livenessProbe:
httpGet:
  path: /api/health
  port: web-interface
periodSeconds: 300
timeoutSeconds: 3
```

The upside would be improved monitoring of the container itself.
