### ISSUE TITLE
Login via Device Impossible due to Timezone Mismatch

### ISSUE THREAD

**Issue by georglauterbach** [bitwarden/self-host#289]
I'm running [BW 2024.8.1-beta](https://hub.docker.com/layers/bitwarden/self-host/2024.8.1-beta/images/sha256-75138ddabbea98cab1e9a7dd0866d21cde05d9b9081ee34df0613b39fd3df01b?context=explore) in a Kubernetes cluster with [k8tz](https://github.com/k8tz/k8tz). k8tz properly sets `/etc/localtime` inside my pods. The BW pod has the correct timezone set: CEST (UTC+2).

My client, the iOS App, receives login requests from the self-hosted server, which is running quite well. The request can never be fulfilled, though, because the request is shown as "2 hours ago", i.e. the request has become invalid. Is there something I am missing, something like "we always use UTC everywhere"? I tested without k8tz before, and had the same issue (i.e. the contents of `/etc/localtime` do not seem to matter).

Any help is appreciated :)

CC @vgrassia

**Comment by keithhubner** [comment]
Hi, can you share your deployment manifest so I can try and reproduce this?
Thanks!

**Comment by georglauterbach** [comment]
<details>
<summary>Deployment</summary>

```yaml
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: bitwarden

  annotations:
    ignore-check.kube-linter.io/run-as-non-root: >-
      Bitwarden needs to run as root
    ignore-check.kube-linter.io/no-read-only-root-fs: >-
      There are too many files written to make the root FS read-only

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden

  template:
    metadata:
      labels:
        app: bitwarden
        app.traefik.io/communication: 'true'

    spec:
      terminationGracePeriodSeconds: 120
      restartPolicy: Always

      dnsConfig:
        options:
          - name: ndots
            value: '1'
          - name: trust-ad
          - name: edns0

      volumes:
        - name: vol-data
          persistentVolumeClaim:
            claimName: bitwarden-data
        - name: vol-tmp
          emptyDir: {}

      hostname: bitwarden
      containers:
        # ref: https://bitwarden.com/de-DE/help/install-and-deploy-unified-beta/
        #      https://github.com/bitwarden/self-host
        - name: bitwarden
          # The [Unified Deployment Open
          # Beta](https://bitwarden.com/blog/new-deployment-option-for-self-hosting-bitwarden/)
          # is used here.
          image: docker.io/bitwarden/self-host:2024.8.2-beta
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            privileged: false
            appArmorProfile:
              type: RuntimeDefault
            capabilities:
              add:
                # file permission capabilities
                - CHOWN
                - FOWNER
                - MKNOD
                - SETGID
                - SETUID
                - DAC_OVERRIDE
                # miscellaneous capabilities
                - SYS_CHROOT
                - SYS_PTRACE
                - KILL
              drop: [ ALL ]
            seccompProfile:
              type: RuntimeDefault

          resources:
            limits:
              memory: 1500Mi
              cpu: '1'
            requests:
              memory: 650Mi
              cpu: 100m

          volumeMounts:
            - name: vol-data
              mountPath: /etc/bitwarden
              readOnly: false
            - name: vol-tmp
              mountPath: /tmp
              readOnly: false

          ports:
            - name: web-interface
              containerPort: 8080
              protocol: TCP

          envFrom:
            # The correct [environment
            # variables](https://bitwarden.com/help/install-and-deploy-unified-beta/#environment-variables)
            # have to be set, e.g., the correct [location](https://bitwarden.com/help/server-geographies/).
            - configMapRef:
                name: bitwarden-environment
            - secretRef:
                name: bitwarden-environment
            - secretRef:
                name: database-environment

          startupProbe:
            httpGet:
              path: /api/alive
              port: web-interface
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/alive
              port: web-interface
            periodSeconds: 300
            failureThreshold: 2
            timeoutSeconds: 5
```
</details>

k8tz uses an additional initContainer

```yaml
  initContainers:
    - name: k8tz
      image: quay.io/k8tz/k8tz:0.16.2
      args:
        - bootstrap
      resources: {}
      volumeMounts:
        - name: k8tz
          mountPath: /mnt/zoneinfo
        - name: kube-api-access-26q5k
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
```

to make `/etc/localtime` point to CEST+2 (Europe/Berlin). It also sets an ENV variable for BitWarden:

```yaml
      env:
        - name: TZ
          value: Europe/Berlin
```
